# Generated by Django 4.0.5 on 2022-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autor_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
